---

- hosts: all
  become: true
  tasks:

  - name: update repository index using apt
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package using apt
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache using apt
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository index using dnf
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache2 package using dnf
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: add php support for apache using dnf
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"
